### ISSUE TITLE
Problems reading High temperatures over 700°C with the MCP9600

### ISSUE THREAD

**Issue by Zaduu** [adafruit/Adafruit_MCP9600#9]
i everyone from Adafruit,
I am trying to create a temperature controller for a high temperature tubular oven with three heating modules witch can be controlled individually. I am Using an Arduino nano an three MCP9600 Board from Adafruit to meassure the temperature an d con troll the SSRs for the Heating coils. The date code from the MCPs is 2043 so it can not be an issue mentioned in the Document(http://ww1.microchip.com/downloads/en/DeviceDoc/MCP9600-Data-Sheet-Errata-80000741C.pdf). Even so I tried to reduce the I2C CLK zi 50kHz. Problem is still there in ll modules. The thermocouples I used are type K high quality industry standard thermocouples. They work over the full temperature range of the oven (1150 °C) with the old PID controllers.
I have programmed a moving average. As a reference I am using my trusty fluke thermocouple reader. It shows that MCP9600 works properly up to about 700°C. Than the values start behaving erratically and more or less the same or are even going down and there is a huge amount of instability in the measurements up to 10°C. The wired thing is also that when I reset the Arduino at this point, after the reset I am getting the proper temperature for a time. Here Is some testdata 
[Rohrofen lineat versuch24.txt](https://github.com/adafruit/Adafruit_CircuitPython_MCP9600/files/8142668/Rohrofen.lineat.versuch24.txt)

there are also some wired temperature jumps downward in the data before it turns crazy. these are already outside of the specifications in the datasheet. here is a random line aut of the data and you can find that in nearly every batch after 200°c. 

![grafik](https://user-images.githubusercontent.com/100430875/155807453-c2f29762-3e1e-4ddc-ad7e-3b3df1bd0f1f.png)

And this behavior basically gets worse the higher the Temperature is. And I do not see these jumps in the fluke . By the way, single values are about 400ms apart.

And here is the code I am using for reading the temperature. 

```c
void gettemp() {

  if (millis() > ttemp + delaytemp) {
    ttemp = millis();
    float tempintermed1 = 0;
    float tempintermed2 = 0;
    float tempintermed3 = 0;
    if (MCP9600a == 1) {
      tempintermed1 =  mcp1.readThermocouple();
    }
    if (MCP9600b == 1) {
      tempintermed2 =  mcp2.readThermocouple();
    }
    if (MCP9600c == 1) {
      tempintermed3 =  mcp3.readThermocouple();
    }
    /*Serial.print(mopsserial);
      if (mopsserial == 1) {
      //Serial.print("Hot Junction: "); Serial.print(tempintermed1);
      Serial.print("  Hot Junction2: "); Serial.print(tempintermed2);
      //Serial.print("  Hot Junction3: "); Serial.println(tempintermed3);
      }*/
    if (isnan(tempintermed1) or isnan(tempintermed2) or isnan(tempintermed3) or tempintermed1 > 1500
        or tempintermed2 > 1500 or tempintermed3 > 1500 or tempintermed1 < 0 or tempintermed2 < 0 or tempintermed3 < 0) { // ignoriere alle Messungen in denen ein Fehler zurück kommt
    } else {
      temparraymovav [0][movav] =  tempintermed1 ;
      temparraymovav [1][movav] =  tempintermed2 ;
      temparraymovav [2][movav] =  tempintermed3 ;
      if (movav == 14) {
        movav = 0;
      } else {
        movav++;
      }
    }
  }
  if (millis() > ttemplcd + delaytemplcd) {
    ttemplcd  = millis();
    for (byte i = 0; i < 3; i++) {
      temp_i_now[i] = average(i);
    }   // berechne Mittelwert der temperatur
    if (millis() > ttempfeedback + 25000 and mopsserial == 1) {
      ttempfeedback = millis();
      for (byte n = 0; n < 3; n++) {
        for (byte i = 0; i < 15; i++) {
          Serial.print(temparraymovav [n][i]); Serial.print(" ");
        }
        temp_i_now[n]; Serial.print("\t");
      }
      Serial.println();
    }
    lcd.setCursor(0, 1);
    if (encodermenue == 0) {
      lcd.print(temp_i_now[0], 1);
      lcd.print((char)223); lcd.print(F("C "));
      lcd.setCursor(0, 2);
      lcd.print(temp_i_now[1], 1);
      lcd.print((char)223); lcd.print(F("C "));
      lcd.setCursor(0, 3);
      lcd.print(temp_i_now[2], 1);
      lcd.print((char)223); lcd.print(F("C "));
    }
    if (ovenon == 0) {
      for (byte i = 0; i < 3; i++) {
        tempalti[i] = temp_i_now[i];
      }
    }
  }
}

float average (byte spalte)  
{
  float sum = 0.0 ;
  for (byte i = 0 ; i < 15 ; i++) {
    sum += temparraymovav [spalte][i];
  }
  sum = sum / 15.0 ;
  return sum;// average will be fractional, so float may be appropriate.
}

```
I already tried to put the MCPs in shutdown mode and waking them up again every minute or so. but there is no effect. I also tried using the mcp1.begin(I2C_ADDRESS1) command to reset the MCP. But that had the wired effect of triggering a reset of the Arduino every tenth try or so witch is canceling the Hetingecontroll. I have ruled out electrical noise by testing the setup by heating up a quartz tube with Thermcouple inside with a bunsenburner. Same issue. I also tested several power supplies and measured there noise in the system with my osziloscope. No visible issues as far a I can see.
I also tried the MAX31855 as an alternative. It works fine no crazy noise issues but we need precise values at over 1000°C and the MAX31855 cannot deliver that
it is all quit puzzling and I am at the end of my wisdom here.
Every help you guys can give is really appreciated

**Comment by Zaduu** [comment]
Ok I have found the issue I think. It is noise, stupid me has not seen it, from the AC curent running throught the heating elements. I could not sleep today because of the issue and so I tested some new code. same issue. I also programmed in some automatic stoop for the heating program and immediately without any restart of the Arduino the temperatures are correct after stopping the heating elements. the puzzeling thing is, that I can not see anything relevant on the osziloscope. And I had the same issue with the bunsenburner. Maybe the issue is in the ADC of the MCP . I already grounded my perforated pcb on witch I build the circuit to the chassy of the oven Heating module before all this but it did not make a difference.  Than I also looked at the adafruit module an the topside of the PCB were the IC sits is not grounded. Maybe it would be a good addition for the next revision to ground the top layer too. 
I will try to get proper shielding for my setup. Any advice is still appriciated

**Comment by dhalbert** [comment]
We have some people with excellent EE background who do support in the forums who may be able to help with this. I will close these issues, since they are not bugs, but you can open an issue in https://forums.adafruit.com. Include photos of the wiring. For instance, are the I2C wires close to the heating wires?
